### ISSUE TITLE
When I purge a chat message, the whole chat gets reset

### ISSUE THREAD

**Issue by chrisyroid** [jhoooooo/streamlabs-chat#7]
First of all, great work.  I'm having a problem though with the chat box getting cleared completely when I purge a message.

The problem seems to be:

`    if (obj.detail.command === "CLEARCHAT") {
        $('#log').empty();
    }`

Which completely deletes the chat instead of purging an individual message.

**Comment by jhoooooo** [comment]
Hello.

Never notice that both /clear and /timeout uses same command id. I will update the themes later during Chinese New Year holidays.

These code should fix the issue. Will test further as I update the themes.
```
if (obj.detail.command === "CLEARCHAT" && typeof obj.detail.tags["ban-duration"] == "undefined") {
        $('#log').empty();
    }
